### PR TITLE
Octree rev 2

### PR DESCRIPTION
**Pull request by jsburke**
Add three new arrays to struct for accelerations per time step

Add funciton to zero out said arrays every timestep, to be used AFTER tree is restructured when it is

### CODE REVIEW

**Comment by jsburke** [comment]
Think every addition looks good.  Just looking for quick review before merging onto master, should only need one person to look at it.

**Comment by sarthakjagetia** [comment]
Looks good to me....

**Comment by rashmi2383** [comment]
Why do we need acceleration vectors?

**Comment by jsburke** [comment]
We need them to update position and velocity correctly and easily at every time step.  I'm afraid we'd get funky results if we did force calculation and position and velocity updates at the same time, because then subsequent bodies are not all using the same positions for their calculations.

If this makes sense, Rashmi, please simply merge

**Pull request merged**
